Updates deploy script

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -56,6 +56,11 @@ then
     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
+if ! git checkout $SRC_BRANCH; then
+  echo "Could not check out source branch $SRC_BRANCH."
+  [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+fi
+  
 # Check if there are any uncommitted changes
 if ! git diff-index --quiet HEAD --; then
     echo "Changes to the following files are uncommitted:"
@@ -91,6 +96,9 @@ git checkout -b $DEPLOY_BRANCH
 
 # Export JEKYLL_ENV=production
 export JEKYLL_ENV=production
+
+# Install dependencies
+bundle install
 
 # Build site
 bundle exec jekyll build
